- name: install nextcloud
  hosts: nextcloud
  become: yes

  vars_prompt:
    - name: nc_user
      prompt: "set nextcloud username"
      private: no
      default: "admin"

    - name: nc_password
      prompt: "set nextcloud password"
      private: yes

  tasks:   
    - name: snap install nextcloud
      community.general.snap:
        name: nextcloud
        state: present
     
    # wait a while for nextcloud to install fully 
    - name: take a breather
      ansible.builtin.pause:
        seconds: 15

    - name: Create Nextcloud account
      ansible.builtin.shell:
        cmd: "nextcloud.manual-install {{ nc_user }} {{ nc_password }}"
        creates: /var/snap/nextcloud/common/nextcloud/data/config.php

    - name: addition to trusted domains
      ansible.builtin.shell:
        cmd: | 
          nextcloud.occ config:system:set trusted_domains 1 --value={{ansible_facts["default_ipv4"]["address"]}}
          nextcloud.occ config:system:set trusted_domains 2 --value=127.0.0.1
          nextcloud.occ config:system:set trusted_domains 3 --value={{ floating_ip }}
