#!/bin/bash

BASTION_IP="198.18.1.181"
NEXTCLOUD_IP="192.168.199.138"

echo "Öppnar tunnel till Nextcloud via Bastion..."
echo "Du kan nu nå Nextcloud på: http://localhost:8080"
echo "Tryck Ctrl+C för att stänga tunneln."

# -L mappar din lokala port 8080 till Nextclouds port 80
# -N säger till SSH att inte starta ett skal (bara hålla tunneln öppen)
ssh -L 8080:$NEXTCLOUD_IP:80 -J ubuntu@$BASTION_IP ubuntu@$NEXTCLOUD_IP -N
